# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-t0vE0cup2bhBJyL-E6gIffC84Osg8GZ
"""

# app.py
import streamlit as st
import joblib

# Loading the model and vectorizer
model = joblib.load("spam_classifier.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# Title
st.title("📩 SMS Spam Classifier")

# User input
user_input = st.text_area("Enter the SMS message:", height=150)

# Predict button
if st.button("Classify"):
    if user_input.strip() == "":
        st.warning("Please enter a message.")
    else:
        # Transform and predict
        input_vector = vectorizer.transform([user_input])
        prediction = model.predict(input_vector)

        # Display result
        if prediction[0] == "spam":
            st.error("🚫 This message is SPAM!")
        else:
            st.success("✅ This message is NOT SPAM.")